apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://172.20.10.7:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://172.20.10.7:3306/foodcataloguedb
  userdb_url: jdbc:mysql://172.20.10.7:3306/userdb
  orderdb_url: mongodb://172.20.10.7:27017/orderdb
  eureka_service_address: http://10.101.174.218:8761/eureka/
